### PR TITLE
fix: babel import type track (close #28)

### LINKED ISSUE #28: babel-import error about importing a type
### SourceCode

```ts
import { InputProps } from "antd";

{
    let InputProps = 1;
    console.log(InputProps);
}

function App(props: InputProps) {}
```

### Expected result

```ts
import { InputProps } from "antd";

{
    let InputProps = 1;
    console.log(InputProps);
}

function App(props: InputProps) {}
```

### Unexpected result

```ts
import "antd/es/input-props/style/index.css";
import { InputProps } from "antd/es/input-props/index.js";
{
    let InputProps = 1;
    console.log(InputProps);
}
function App(props: InputProps) {}
```

That is because babel-import not call `resolve` first, which make type resolving `mark` incorrectly.

## How to Fix

- call `resolver` first to make `mark` correctly
- if a type is referenced, still remain it in origin `import`.

for example
```ts
import { InputProps, Input } from 'antd'
```
should be
```ts
import "antd/es/input/style/index.css";
import Input from "antd/es/input/index.js";
import { InputProps } from 'antd'
```

### PR DESCRIPTION
**Pull request by konicyQWQ**
## Intro
- Fix type track bug (call `resolver` first)
- only tree shaking unused component or typed, **if a type is referenced, program won't delete.**
- simplify some code use `and_then`, `then`
- add a test case

### CODE REVIEW

File: crates/speedy-transform/src/web_transform/babel_import.rs [hunk 1]
```diff
@@ -44,35 +54,27 @@ pub fn transform_style(
...
           match specifier {
             ImportSpecifier::Named(ref s) => {
-              let imported = match &s.imported {
-                Some(imported) => match &imported {
-                  ModuleExportName::Ident(ident) => Some(ident.sym.to_string()),
-                  ModuleExportName::Str(ident) => Some(ident.value.to_string()),
-                },
-                None => None,
-              };
+              let imported = s.imported.as_ref().and_then(|imported| match imported {
```
Comment (h-a-n-a) [inline crates/speedy-transform/src/web_transform/babel_import.rs]: It's better to use `map` here to avoid manual `Option` wraps

File: crates/speedy-transform/src/web_transform/babel_import.rs [hunk 2]
```diff
@@ -44,35 +54,27 @@ pub fn transform_style(
...
+              });
               // 当 imported 不为 none 时, local.sym 是引入组件的 as 别名
-              let as_name: Option<String> = if imported.is_some() {
-                Some(s.local.sym.to_string())
-              } else {
-                None
-              };
+              let as_name: Option<String> = imported.is_some().then(|| s.local.sym.to_string());
               // 当 imported 不为 none 时, 实际引入的组件命名为 imported, 否则为 s.local.sym
               let ident: String = imported.unwrap_or(s.local.sym.to_string());
```
Comment (h-a-n-a) [inline crates/speedy-transform/src/web_transform/babel_import.rs]: `unwrap_or_else`

**Review by h-a-n-a — CHANGES_REQUESTED** [review]

File: node/__tests__/unit.spec.ts [hunk 3]
```diff
@@ -223,6 +274,7 @@ import { Radio } from "antd/es/radio/index.js";
 import { Input } from "antd/es/input/index.js";
 import React from "react";
 import ReactDOM from "react-dom";
+import { InputProps } from "antd";
```
Comment (h-a-n-a) [inline node/__tests__/unit.spec.ts:279]: This seems not as expected since the code generation result doesn't contain the type reference to that or it's a bug with SWC

File: crates/speedy-transform/src/web_transform/babel_import.rs (hunk 1 above)
Comment (konicyQWQ) [reply crates/speedy-transform/src/web_transform/babel_import.rs]: fix

File: crates/speedy-transform/src/web_transform/babel_import.rs (hunk 2 above)
Comment (konicyQWQ) [reply crates/speedy-transform/src/web_transform/babel_import.rs]: fix

File: node/__tests__/unit.spec.ts (hunk 3 above)
Comment (konicyQWQ) [reply node/__tests__/unit.spec.ts:279]: It seems a bug of SWC🧐. I didn't remove any type. But  `Props` in `class Page extends React.Component<Props,any>` disappear.

I add a new line `type Props = InputProps;` into test case. This line remains but only the class super type disappear😂

Comment (h-a-n-a) [reply node/__tests__/unit.spec.ts:279]: LGTM

**Review by h-a-n-a — APPROVED** [review]
