### PR TITLE
fix: make tsx parse a config (close #36)

### LINKED ISSUE #36: tsx always true will cause error for some cases
```ts
const urlQuerys = <string>getQuery();
```

- This code can be correctly parsed when it is `*.ts`.
    - https://www.typescriptlang.org/play?jsx=0&ts=4.8.0-beta#code/MYewdgzgLgBArgJwDYEU4FMEE8IwLwwA80CAlmAOYB8F6UamWAFAJQDcQA
- But it will failed when it is `*.tsx`.
    - https://www.typescriptlang.org/play?ts=4.8.0-beta#code/MYewdgzgLgBArgJwDYEU4FMEE8IwLwwA80CAlmAOYB8F6UamWAFAJQDcQA

## Fix

speedy-napi should provide a config that can close `tsx` parse, only use `ts`

### PR DESCRIPTION
**Pull request by konicyQWQ**
Bug see [https://github.com/speedy-js/speedy-native/issues/36](https://github.com/speedy-js/speedy-native/issues/36).

## Code

-  add a config `tsx: Option<bool>`.
- when `tsx` is `false`, swc only parse typescript, no tsx.
- add some test case

### CODE REVIEW

File: crates/speedy-transform/src/web_transform/parser.rs [hunk 1]
```diff
@@ -30,10 +30,16 @@ pub fn transform(
...
+  let tsx_parse = config.tsx.unwrap_or(true);
+  // wasm plugin parse option is in js side, not in rust side
+  #[cfg(target_arch = "wasm32")]
+  let tsx_parse = true;
+
   let lexer = Lexer::new(
     // We want to parse ecmascript
     Syntax::Typescript(TsConfig {
-      tsx: true,
+      tsx: tsx_parse,
```
Comment (h-a-n-a) [inline crates/speedy-transform/src/web_transform/parser.rs]: For this PR, this newly added option looks good to me. 
However, It comes to my mind that we should not treat any input files as `TypeScript` formatted. For JavaScript-like sources like `js` or `jsx`, it should complain this behavior as an error. But we should think if we might need to add this in a backward-compatible way.

Comment (konicyQWQ) [reply crates/speedy-transform/src/web_transform/parser.rs]: Maybe we should use config like `code_type: Option<String>`.
It can be `js`, `jsx`, `ts`, `tsx`, which means what type users want to parse. But of course, default and illegal string will use `tsx` parse.

see new change.

Comment (h-a-n-a) [reply crates/speedy-transform/src/web_transform/parser.rs]: It will be better to use `enum`, but regarding of the current architecture with node binding and wasm. It looks good to me.

**Review by h-a-n-a — APPROVED** [review]
